# Generated by Django 3.0.8 on 2021-08-18 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(blank=True, max_length=240, null=True)),
                ('icono', models.CharField(blank=True, default='local_movies', max_length=240, null=True)),
                ('ruta', models.CharField(blank=True, choices=[('home', 'home'), ('MenusAdministrar', 'MenusAdministrar')], default='MenusAdministrar', max_length=240, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('titulo', models.CharField(help_text='Titulo', max_length=255)),
                ('subtitulo', models.CharField(blank=True, help_text='subtitulo', max_length=255, null=True)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, help_text='duracion', max_length=255, null=True)),
                ('sinopsis', models.TextField(blank=True, help_text='sinopsis', null=True)),
                ('reparto', models.CharField(blank=True, help_text='reparto', max_length=255, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='bita_archivos')),
                ('triller', models.TextField(blank=True, help_text='triller', null=True)),
                ('ruta', models.CharField(blank=True, choices=[('PeliculasDetalle', 'PeliculasDetalle')], default='PeliculasDetalle', max_length=240, null=True)),
                ('vistas', models.IntegerField(blank=True, default=0, null=True)),
                ('carousel', models.BooleanField(default=False, help_text='carousel')),
                ('imagen_carousel', models.FileField(blank=True, null=True, upload_to='bita_archivos')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelicula_created', related_query_name='peliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelicula_update', related_query_name='peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_peliculas',
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'db_table': 'principal_servidores',
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='ServidorPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('link', models.TextField(blank=True, help_text='link del embed', null=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_pelicula', to='principal.Pelicula')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_servidor', to='principal.Servidor')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidorpelicula_created', related_query_name='servidorpeliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidorpelicula_update', related_query_name='servidorpeliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_servidores_peliculas',
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='servidor_pelicula',
            field=models.ManyToManyField(through='principal.ServidorPelicula', to='principal.Pelicula'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_created', related_query_name='servidors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servidor',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_update', related_query_name='servidors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MenuPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('vistas', models.IntegerField(blank=True, default=0, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_menu', to='principal.Menu')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp_pelicula', to='principal.Pelicula')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menupelicula_created', related_query_name='menupeliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menupelicula_update', related_query_name='menupeliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_menus_peliculas',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_pelicula',
            field=models.ManyToManyField(through='principal.MenuPelicula', to='principal.Pelicula'),
        ),
        migrations.AddField(
            model_name='menu',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_created', related_query_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_update', related_query_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', null=True, verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', null=True, verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('texto', models.CharField(blank=True, max_length=240, null=True)),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busqueda_created', related_query_name='busquedas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busqueda_update', related_query_name='busquedas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_busquedas',
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
